-- FlexFam — Supabase schema + row level security
-- Run this whole file in the Supabase SQL editor. It is safe to re-run.

-- ============================================================
-- 1. Tables
-- ============================================================

create table if not exists public.events (
  id         bigint generated by default as identity primary key,
  type       text not null,
  page       text,
  path       text,
  title      text,
  ref        text,
  vid        text,
  lang       text,
  ua         text,
  day        date,
  ts_client  timestamptz default now(),
  url        text,
  label      text,
  task_title text,
  task_id    text,
  payout     numeric
);

create table if not exists public.campaigns (
  id          bigint generated by default as identity primary key,
  campaign_id text,
  platform    text,
  action      text,
  title       text,
  url         text,
  payout      numeric,
  owner       text,
  source      text,
  day         date,
  ts_client   timestamptz default now()
);

-- Admin allowlist. This is the single source of truth for who may read
-- analytics. The email list in assets/js/supabase-config.js is only a UI
-- hint — it is public and trivially editable, so it must never be trusted.
create table if not exists public.admins (
  email      text primary key,
  created_at timestamptz default now()
);

-- Indexes the admin dashboard actually queries on.
create index if not exists events_ts_client_idx on public.events (ts_client desc);
create index if not exists events_type_idx      on public.events (type);
create index if not exists events_day_idx       on public.events (day);
create index if not exists campaigns_ts_idx     on public.campaigns (ts_client desc);

-- ============================================================
-- 2. Seed your admin account(s)
-- ============================================================
-- Keep this in sync with window.FF_ADMIN_EMAILS in supabase-config.js.
-- The email must match the Supabase Auth user you log in with.
insert into public.admins (email) values
  ('ravanyt001@gmail.com')
on conflict (email) do nothing;

-- ============================================================
-- 3. Helper: is the current request an allowlisted admin?
-- ============================================================
-- security definer so the function can read public.admins even though
-- that table's own RLS blocks anon. search_path is pinned to avoid
-- search_path hijacking, which is a real risk with security definer.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admins a
    where lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- ============================================================
-- 4. Row level security
-- ============================================================

alter table public.events    enable row level security;
alter table public.campaigns enable row level security;
alter table public.admins    enable row level security;

-- Re-runnable: drop before create.
drop policy if exists "public can insert events"     on public.events;
drop policy if exists "public can insert campaigns"  on public.campaigns;
drop policy if exists "admins can read events"       on public.events;
drop policy if exists "admins can read campaigns"    on public.campaigns;
drop policy if exists "admins can read admins"       on public.admins;

-- Anonymous visitors may only APPEND analytics. They cannot read, update
-- or delete anything — no select policy for anon means no data leaks.
create policy "public can insert events"
  on public.events for insert
  to anon, authenticated
  with check (true);

create policy "public can insert campaigns"
  on public.campaigns for insert
  to anon, authenticated
  with check (true);

-- Only logged-in allowlisted admins can read the analytics.
create policy "admins can read events"
  on public.events for select
  to authenticated
  using (public.is_admin());

create policy "admins can read campaigns"
  on public.campaigns for select
  to authenticated
  using (public.is_admin());

-- An admin may see the allowlist; nobody can modify it from the browser.
-- Add or remove admins from the Supabase SQL editor / dashboard only.
create policy "admins can read admins"
  on public.admins for select
  to authenticated
  using (public.is_admin());

-- Note: no update or delete policy exists on any table by design, so
-- analytics rows are append-only from every browser client.
