-- ============================================================
-- FLEXFAM — MINING SCHEMA SYNC (fix: "record has no field …")
--
-- KYA HAI YE: Live database ki mining tables purane version se
-- hain, naye RPC naye columns padhte hain -> error. Ye SQL har
-- possibly-missing column add kar deta hai (existing data safe).
--
-- Run karo, PHIR supabase-mining.sql (SQL A) dobara run karo.
-- Safe to re-run.
-- ============================================================

-- ---------- tables (agar purani install me koi table hi nahi bana) ----------
create table if not exists public.mining_config (
  id                 int primary key default 1 check (id = 1),
  usd_per_ghs_day    numeric not null default 0.00105,
  maintenance_pct    numeric not null default 8,
  invest_boost_min_usd numeric not null default 10,
  invest_boost_pct   numeric not null default 20,
  custom_min_ghs     int     not null default 100,
  custom_max_ghs     int     not null default 20000,
  custom_min_days    int     not null default 7,
  custom_max_days    int     not null default 365,
  custom_base_days   int     not null default 30,
  min_claim_usdt     numeric not null default 0.05,
  points_bonus_pct   numeric not null default 10,
  boost_pct          numeric not null default 25,
  boost_hours        int     not null default 8,
  boost_cooldown_h   int     not null default 24,
  points_per_usdt    int     not null default 1000,
  updated_at         timestamptz not null default now()
);
insert into public.mining_config (id) values (1) on conflict (id) do nothing;

create table if not exists public.mining_plans (
  key        text primary key,
  name       text    not null,
  tag        text    not null default '',
  ghs        int     not null check (ghs > 0),
  days       int     not null check (days > 0),
  price_usd  numeric not null default 0 check (price_usd >= 0),
  color      text    not null default '#7c3aed',
  is_free    boolean not null default false,
  featured   boolean not null default false,
  perks      text[]  not null default '{}',
  sort       int     not null default 0,
  active     boolean not null default true
);

create table if not exists public.mining_custom_tiers (
  up_to       int     primary key,
  usd_per_ghs numeric not null check (usd_per_ghs > 0)
);

create table if not exists public.balances (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  usdt       numeric not null default 0,
  points     bigint  not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.mining_accounts (
  user_id     uuid primary key references auth.users(id) on delete cascade,
  unclaimed   numeric not null default 0,
  claimed     numeric not null default 0,
  last_accrue timestamptz not null default now(),
  boost_until timestamptz,
  last_boost  timestamptz
);

create table if not exists public.mining_contracts (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  plan        text not null,
  name        text not null,
  ghs         int  not null check (ghs > 0),
  days        int  not null check (days > 0),
  started_at  timestamptz not null default now(),
  ends_at     timestamptz not null,
  price_usd   numeric not null default 0,
  paid_with   text    not null check (paid_with in ('usdt', 'points', 'free')),
  paid_amount numeric not null default 0,
  earned      numeric not null default 0,
  status      text    not null default 'active' check (status in ('active', 'expired'))
);

create table if not exists public.mining_ledger (
  id      bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type    text not null,
  detail  text not null default '',
  amount  numeric not null default 0,
  at      timestamptz not null default now()
);

-- ---------- mining_config ----------
alter table public.mining_config add column if not exists usd_per_ghs_day      numeric not null default 0.00105;
alter table public.mining_config add column if not exists maintenance_pct     numeric not null default 8;
alter table public.mining_config add column if not exists invest_boost_min_usd numeric not null default 10;
alter table public.mining_config add column if not exists invest_boost_pct    numeric not null default 20;
alter table public.mining_config add column if not exists custom_min_ghs      int     not null default 100;
alter table public.mining_config add column if not exists custom_max_ghs      int     not null default 20000;
alter table public.mining_config add column if not exists custom_min_days     int     not null default 7;
alter table public.mining_config add column if not exists custom_max_days     int     not null default 365;
alter table public.mining_config add column if not exists custom_base_days    int     not null default 30;
alter table public.mining_config add column if not exists min_claim_usdt      numeric not null default 0.05;
alter table public.mining_config add column if not exists points_bonus_pct    numeric not null default 10;
alter table public.mining_config add column if not exists boost_pct           numeric not null default 25;
alter table public.mining_config add column if not exists boost_hours         int     not null default 8;
alter table public.mining_config add column if not exists boost_cooldown_h    int     not null default 24;
alter table public.mining_config add column if not exists points_per_usdt     int     not null default 1000;
alter table public.mining_config add column if not exists updated_at          timestamptz not null default now();

-- ---------- mining_plans ----------
alter table public.mining_plans add column if not exists tag       text    not null default '';
alter table public.mining_plans add column if not exists price_usd numeric not null default 0;
alter table public.mining_plans add column if not exists color     text    not null default '#7c3aed';
alter table public.mining_plans add column if not exists is_free   boolean not null default false;
alter table public.mining_plans add column if not exists featured  boolean not null default false;
alter table public.mining_plans add column if not exists perks     text[]  not null default '{}';
alter table public.mining_plans add column if not exists sort      int     not null default 0;
alter table public.mining_plans add column if not exists active    boolean not null default true;
alter table public.mining_plans add column if not exists ghs       int     not null default 1;
alter table public.mining_plans add column if not exists days      int     not null default 1;

-- ---------- mining_custom_tiers ----------
alter table public.mining_custom_tiers add column if not exists usd_per_ghs numeric not null default 0.02;

-- ---------- balances ----------
alter table public.balances add column if not exists usdt       numeric not null default 0;
alter table public.balances add column if not exists points     bigint  not null default 0;
alter table public.balances add column if not exists updated_at timestamptz not null default now();

-- ---------- mining_accounts ----------
alter table public.mining_accounts add column if not exists unclaimed   numeric not null default 0;
alter table public.mining_accounts add column if not exists claimed     numeric not null default 0;
alter table public.mining_accounts add column if not exists last_accrue timestamptz not null default now();
alter table public.mining_accounts add column if not exists boost_until timestamptz;
alter table public.mining_accounts add column if not exists last_boost  timestamptz;

-- ---------- mining_contracts ----------
alter table public.mining_contracts add column if not exists plan        text    not null default 'custom';
alter table public.mining_contracts add column if not exists name        text    not null default 'Rig';
alter table public.mining_contracts add column if not exists started_at  timestamptz not null default now();
alter table public.mining_contracts add column if not exists price_usd   numeric not null default 0;
alter table public.mining_contracts add column if not exists paid_with   text    not null default 'free';
alter table public.mining_contracts add column if not exists paid_amount numeric not null default 0;
alter table public.mining_contracts add column if not exists earned      numeric not null default 0;
alter table public.mining_contracts add column if not exists status      text    not null default 'active';
alter table public.mining_contracts add column if not exists ghs         int     not null default 1;
alter table public.mining_contracts add column if not exists days        int     not null default 1;

-- ---------- mining_ledger ----------
alter table public.mining_ledger add column if not exists type   text    not null default 'info';
alter table public.mining_ledger add column if not exists detail text    not null default '';
alter table public.mining_ledger add column if not exists amount numeric not null default 0;
alter table public.mining_ledger add column if not exists at     timestamptz not null default now();
