-- Run in Supabase SQL editor
create table if not exists public.events (id bigint generated by default as identity primary key, type text not null, page text, path text, title text, ref text, vid text, lang text, ua text, day date, ts_client timestamptz default now(), url text, label text, task_title text, task_id text, payout numeric);
create table if not exists public.campaigns (id bigint generated by default as identity primary key, campaign_id text, platform text, action text, title text, url text, payout numeric, owner text, source text, day date, ts_client timestamptz default now());
alter table public.events enable row level security; alter table public.campaigns enable row level security;
create policy "public can insert events" on public.events for insert to anon with check (true);
create policy "public can insert campaigns" on public.campaigns for insert to anon with check (true);
-- Add a SELECT policy for your admin JWT/email if you need the admin dashboard to read rows.
